### ISSUE TITLE
Add support for GraphQL syntax

### ISSUE THREAD

**Issue by declension** [jgm/skylighting#103]
First of all, thanks for a great project!

GraphQL is pretty popular now, and it'd be great to have support for this in Skylighting. 

There is an [official spec](http://spec.graphql.org/), and quite a few existing highlighters / mini-IDEs (e.g. https://github.com/prisma-labs/graphql-playground)  out there.

**Comment by jgm** [comment]
We'd need a KDE style xml syntax definition for it.
Looks like there's one already in the official repo.
https://invent.kde.org/frameworks/syntax-highlighting/-/blob/master/data/syntax/graphql.xml

**Comment by jgm** [comment]
Added in commit 366492c6d4993691f541b9dc3a493a88344b05b8

**Comment by declension** [comment]
Amazing - thanks!
