### ISSUE TITLE
Version 0.10.2 breaks highlighting for Haskell chars

### ISSUE THREAD

**Issue by abhin4v** [jgm/skylighting#116]
[This commit](https://github.com/jgm/skylighting/commit/cbf0abe37369faddcaff5965b41b9ea520134066) for the file `skylighting-core/xml/haskell.xml` undid the changes done in #40 and broke the highlighting for Haskell chars. Please undo the changes for `haskell.xml` by reimplementing PR #40.

**Comment by jgm** [comment]
I can do that. But it would be nice if someone would fix upstream (KDE syntax definition) so this doesn't happen again.

**Comment by jgm** [comment]
Should be fixed in 0.10.3.
