### ISSUE TITLE
Haskell highlighting is broken

### ISSUE THREAD

**Issue by abhin4v** [jgm/skylighting#120]
Haskell code highlighting with version 0.8.5:

<img width="710" alt="image" src="https://user-images.githubusercontent.com/34121/111805921-78ce0780-88f7-11eb-981e-a2138c9424d2.png">

Haskell code highlighting with version 0.10.4.1:

<img width="664" alt="image" src="https://user-images.githubusercontent.com/34121/111806114-ab780000-88f7-11eb-99fd-3cccab7c10db.png">

I suspect it has something to do with the way Haskell characters are detected.

Code snippet in the image for testing purpose:

```haskell
jsonChar :: Parser String Char
jsonChar =   string "\\\"" $> '"'
         <|> string "\\\\" $> '\\'
         <|> string "\\/"  $> '/'
         <|> string "\\b"  $> '\b'
         <|> string "\\f"  $> '\f'
         <|> string "\\n"  $> '\n'
         <|> string "\\r"  $> '\r'
         <|> string "\\t"  $> '\t'
         <|> unicodeChar
         <|> satisfy (\c -> not (c == '\"' || c == '\\' || isControl c))
  where
    unicodeChar =
      chr . fromIntegral . digitsToNumber 16 0
        <$> (string "\\u" *> replicateM 4 hexDigit)

    hexDigit = digitToInt <$> satisfy isHexDigit

digitsToNumber :: Int -> Integer -> [Int] -> Integer
digitsToNumber base =
  foldl (\num d -> num * fromIntegral base + fromIntegral d)
```

**Comment by jgm** [comment]
Simpler case:
```
c = '"' -- this fails
```
Here the comment is parsed as a StringTok.

**Comment by jgm** [comment]
I see the problem. I made a mistake when reimplementing PR #40 (DetectChar instead of RegExpr).  Should have a fix shortly.
