### ISSUE TITLE
Is it sufficient to update the xml at invent.kde.org?

### ISSUE THREAD

**Issue by andreasabel** [jgm/skylighting#130]
I updated agda.xml upstream (https://invent.kde.org/frameworks/syntax-highlighting/-/merge_requests/225).

- Is this sufficient to get the change into the next release of skylighting?
  (I see that upstream is pulled at least once in a while, see 0bf37aae1d1a1ab8f2086dff39aa80f7af00e92d).
- Do you want to be alerted of changes upstream?
- How often is upstream pulled?

These questions are not clarified by the README, it only says that additions to skylighting should _also_ be added upstream (https://github.com/jgm/skylighting/commit/838367f2806c1a70dc00172cd30e0c3517ce4e04).

Suggested action: integrate answers to above questions into the README.

**Comment by jgm** [comment]
I usually pull upstream before each release.  Sometimes the changes can lead to issues, like #118, which require deeper fixes in skylighting. In that case I'll sometimes cherry-pick changes.
I can bring in the agda changes now to ensure they'll be in the next releaes.
