### ISSUE TITLE
skylighting-extract has no version

### ISSUE THREAD

**Issue by andreasabel** [jgm/skylighting#132]
I wanted to check which version of `skylighting-extract` is installed, but it seems to have very rudimentary command-line handling that does not support to print the version:
```
$ skylighting-extract --version
skylighting-extract: --version: openBinaryFile: does not exist (No such file or directory)
```

**Comment by jgm** [comment]
True, it's a very simple program.  It's really just intended for use by developers; the release tarball for skylighting can be built without it, and in general users shouldn't be installing it.  I don't know if it's worth building `--version` in, but I'd have no objections to a simple PR that does this (preferably without new build dependencies).

**Comment by jgm** [comment]
Now that I've changed the build instructions so that skylighting-extract isn't installed at all, but just run from the build directory, I don't think a version is really needed.
