### ISSUE TITLE
Parsing bug with exact Counting

### ISSUE THREAD

**Issue by Agnishom** [jgm/skylighting#133]
According to [regex101](https://regex101.com/), the regex `a{10}b` should match exactly 10 copies of `a`. The cod at [link](https://github.com/jgm/skylighting/blob/eb89adc8e573865d4078c83faba5daf85d574a68/skylighting-core/src/Regex/KDE/Compile.hs#L92) misparses this.

Replacing this by the following should do the trick:

```haskell
       minn <- option Nothing $ readMay . U.toString <$> A.takeWhile isDig
      comma <- option False (char ',' *> pure True)
      maxn <- case comma of
                False -> pure Nothing
                True -> option Nothing (readMay . U.toString <$> A.takeWhile isDig)
      _ <- char '}'
      case (minn, comma, maxn) of
          (Nothing, _, Nothing) -> mzero
          (Just n, True, Nothing)  -> return $! atleast n re
          (Nothing, True, Just n)  -> return $! atmost n re
          (Just n, False, Nothing) -> return $! between n n re
          (Just m, True, Just n)   -> return $! between m n re
```

**Comment by jgm** [comment]
Thanks!  I went for a slightly different fix that should do the same thing, but it would be great if you could look it over in case I made a mistake.

**Comment by Agnishom** [comment]
This seems to work! Thanks
