### ISSUE TITLE
update xml's to get Nix syntax highlighting

### ISSUE THREAD

**Issue by MMesch** [jgm/skylighting#149]
Any chance that the xml highlighting files will be updated? Specifically it would be great to get highlighting for Nix which is already in here: https://github.com/KDE/syntax-highlighting/tree/master/data/syntax . I thought I won't open a PR directly since I don't know whether you bulk update these xml files.

**Comment by jgm** [comment]
Yes, I can add nix.

**Comment by MMesch** [comment]
Cool thanks for reacting so quickly!

**Comment by jgm** [comment]
yes, probably next release
