### ISSUE TITLE
Add 'gap' language

### ISSUE THREAD

**Issue by ChrisJefferson** [jgm/skylighting#167]
Hi,

I want to use the 'gap' language (already upstream at: https://github.com/KDE/syntax-highlighting/blob/master/data/syntax/gap.xml ). I'm not totally sure how languages get added to skylighting? Are they only added when requested, or does some work need to be done on the upstream GAP syntax file?

**Comment by jgm** [comment]
No work needs to be done, but I don't add the whole kitchen sink in order not to slow down compile times and bloat the binary.

**Comment by jgm** [comment]
Note that you can already use this language by loading the syntax file dynamically.  `--syntax-definition` with pandoc.

**Comment by ChrisJefferson** [comment]
One suggestion -- could there be a directory where I can put syntax definition files (or does one already exist?)

I'm not sure if this should be a suggestion here, or maybe in pandoc ( which already has `--data-dir`, so maybe syntax files could be stored in there?)

I suggest this as I'm using a program which uses pandoc, and I'm having trouble passing arguments (although I have hacked around that by making a pandoc wrapping script).
