### ISSUE TITLE
`Skylighing.Syntax` module listed in `skylighting` cabal file is missing 

### ISSUE THREAD

**Issue by MangoIV** [jgm/skylighting#175]
Hi, the module `Skylighting.Syntax` listed in the cabal file of `skylighting` is not actually present in `src`

**Comment by jgm** [comment]
It's not in the repository, because it's a generated file.
Read the instructions in README.md under Installing to see how to generate them.

**Comment by jgm** [comment]
Or just use `cabal get skylighting` to get the source (including generated files) from the Hackage repository.

**Comment by MangoIV** [comment]
Yeah I realised. This is uhm... quite interesting.
