### ISSUE TITLE
KDE theme parser fails on ARGB values

### ISSUE THREAD

**Issue by MangoIV** [jgm/skylighting#178]
in themes that specify colors in ARGB, like the latte theme from catpuccin, the json parser fails.

**Comment by jgm** [comment]
Can you link to the theme file and say what ARGB is?

**Comment by MangoIV** [comment]
This is an example line from the Catpuccin ksyntaxhighligting repo `latte.theme` file https://github.com/catppuccin/ksyntaxhighlighting/blob/5d1496b1f4743676800245ec773dc42460709bee/themes/latte.theme#L988

ARGB seems to be alpha + rgb, so if you want full opaque you prefix with FF and so on.

**Comment by jgm** [comment]
We could easily have it ignore the first two digits in this case.
Adding actual support for opacity would be more involved.
