### ISSUE TITLE
Syntax files in KDE, but not in skylighting

### ISSUE THREAD

**Issue by KyleOndy** [jgm/skylighting#18]
What are the plans for styles that exist the the [KDE](https://github.com/KDE/syntax-highlighting/tree/master/data/syntax) repo but not his repo?

Is it as simple as what was just done for the powershell syntax in #16?

If so, I would be happy to put in the work to incorporate them, either with a single PR or one each.

The list of filetypes in KDE but not skyligthing follow:
```
4dos.xml
abap.xml
adblock.xml
ahdl.xml
ahk.xml
ample.xml
ansforth94.xml
ansic89.xml
ansys.xml
apparmor.xml
asm6502.xml
asm-avr.xml
asm-dsp56k.xml
asm-m68k.xml
asterisk.xml
bitbake.xml
bmethod.xml
carto-css.xml
ccss.xml
cgis.xml
cg.xml
chicken.xml
cisco.xml
clipper.xml
component-pascal.xml
context.xml
crk.xml
cubescript.xml
cue.xml
debianchangelog.xml
debiancontrol.xml
desktop.xml
dosbat.xml
doxyfile.xml
euphoria.xml
e.xml
fastq.xml
ferite.xml
fgl-4gl.xml
fgl-per.xml
freebasic.xml
fstab.xml
ftl.xml
gap.xml
gcode.xml
gdb.xml
gdl.xml
gettext.xml
git-ignore.xml
gitolite.xml
git-rebase.xml
glosstex.xml
gnuplot.xml
grammar.xml
groovy.xml
haml.xml
hunspell-aff.xml
hunspell-dat.xml
hunspell-dic.xml
hunspell-idx.xml
idconsole.xml
idl.xml
ilerpg.xml
inform.xml
intelhex.xml
jam.xml
jira.xml
j.xml
kbasic.xml
kconfig.xml
kdesrc-buildrc.xml
k.xml
ldif.xml
ld.xml
less.xml
logtalk.xml
lpc.xml
lsl.xml
m3u.xml
mab.xml
magma.xml
mako.xml
mason.xml
mel.xml
mergetagtext.xml
meson.xml
metamath.xml
modelica.xml
mup.xml
nagios.xml
nemerle.xml
nesc.xml
nsis.xml
ocamllex.xml
ocamlyacc.xml
oors.xml
opal.xml
pango.xml
pgn.xml
picsrc.xml
pig.xml
pli.xml
ply.xml
pony.xml
povray.xml
ppd.xml
praat.xml
progress.xml
protobuf.xml
pug.xml
puppet.xml
qdocconf.xml
qmake.xml
qml.xml
q.xml
rapidq.xml
replicode.xml
rexx.xml
rib.xml
rmarkdown.xml
rpmspec.xml
rsiidl.xml
rtf.xml
sather.xml
scss.xml
sieve.xml
sisu.xml
sml.xml
spice.xml
sql-oracle.xml
stata.xml
stl.xml
systemc.xml
systemverilog.xml
tads3.xml
taskjuggler.xml
template-toolkit.xml
textile.xml
tibasic.xml
tiger.xml
toml.xml
txt2tags.xml
uscript.xml
vala.xml
valgrind-suppression.xml
varnish4.xml
varnishcc4.xml
varnishcc.xml
varnishtest4.xml
varnishtest.xml
varnish.xml
vcard.xml
velocity.xml
vera.xml
vrml.xml
wavefront-obj.xml
winehq.xml
wml.xml
xharbour.xml
xmldebug.xml
xonotic-console.xml
yacas.xml
yang.xml
zonnon.xml
```

**Comment by KyleOndy** [comment]
Thinking out loud here...
----
Would it be preferable, or possible even, to make KDE's repo a submodule or sub tree of this repo so lessen the maintenance burden on adding and updating the xml files?

This would let KDE do the heavy work of managing the xml files, while this repo exposes them all to the haskell world.

**Comment by jgm** [comment]
I don't want to bring them all in; it already takes a long
time to compile skylighting, and the library gets bigger
each time we add a syntax.  So I try to restrict to a subset
of the most used ones.  You can always add others
dynamically if you need them.

+++ Kyle Ondy [Sep 28 17 16:24 ]:

**Comment by KyleOndy** [comment]
That sounds like a reasonable response to me. Is there any existing documentation or examples on loading additional syntax files dynamically?

If there is not, I will try and create some.

**Comment by jgm** [comment]
If you're using pandoc, the upcoming 2.0 release will have a `--syntax-definition` option.

If you're using this as a library, then see the Haddock documentation.
