### ISSUE TITLE
`network` as a transitive dependency

### ISSUE THREAD

**Issue by nishanthkarthik** [jgm/skylighting#189]
I tried compiling this for wasm and noticed a dependency chain `xml-conduit -> conduit-extra -> network`. Ideally, using skylighting-core should not require my target platform to have networking. Do you have a suggestions for a different xml library that's compatible with xml-conduit?

**Comment by jgm** [comment]
No.  We used to use xml-light, but it doesn't have the features we need to correctly parse KDE syntax descriptions.  At the time I also looked at other alternatives.

**Comment by nishanthkarthik** [comment]
No worries! I'll stub the network calls then :)
