### ISSUE TITLE
Highlighting for Terraform

### ISSUE THREAD

**Issue by mahalel** [jgm/skylighting#190]
Hey, I am trying to see if it is possible to include syntax highlighting for Terraform code. 
As far as I can tell, this is already present in [upstream KDE package](https://github.com/KDE/syntax-highlighting/blob/master/data/syntax/terraform.xml) so just checking if that can be considered please.

**Comment by kquick** [comment]
It looks like this file was added to the top-level `skylighting-core` directory and perhaps should have been in `skylighting-core/xml` instead?

**Comment by jgm** [comment]
Indeed!  Sorry about that.

**Comment by jgm** [comment]
I will fix it.
