### ISSUE TITLE
Proposal for style file distribution via data files

### ISSUE THREAD

**Issue by kquick** [jgm/skylighting#191]
I would like to propose that the XML syntax files referenced [here in the cabal file](https://github.com/jgm/skylighting/blob/master/skylighting-core/skylighting-core.cabal#L29-L30) be moved from being `extra-source-files` to instead being specified as `data-files` as described [in the cabal specification](https://cabal.readthedocs.io/en/3.10/cabal-package.html#pkg-field-data-files) which would cause them to be installed alongside the library object files.  In addition, a function could be added (perhaps `Skylighting.Loader.loadFromInstalledLocation` which would perform the load using the information from [the `getDataDir` provided by](https://cabal.readthedocs.io/en/3.10/cabal-package.html#accessing-data-files-from-package-code) the  (newly added) auto-generated `Path_skylighting_core` module.

The advantage of this is that the XML syntax files would then be available to any application using the `skylighting-core` library without that application needing to supply those files directly or via other means.

Please let me know if the above sounds reasonable and if there are any modifications you would make to this proposal.  If this seems reasonable, I'm happy to generate a pull request with the associated changes.

**Comment by jgm** [comment]
Can you say more about why you'd want this?  Is it because you want to use skylighting-core without skylighting (which contains the tokenizers compiled from the XML definitions)?  Why not just use skylighting, which will give better performance?

**Comment by kquick** [comment]
I am in a situation similar to the original skylighting-core split: I have an application that cannot be GPL licensed, which skylighting-core allows, but not skylighting.  I would prefer to simply defer to skylighting-core's collection of syntax maps rather than duplicating that in my application's package.

**Comment by jgm** [comment]
I see.  I'm not sure it's a good idea.  The change would add 6.4M of installed content for everyone who installs skylighting-core (or e.g. pandoc).  And it would only be useful in unusual cases like yours.

**Comment by kquick** [comment]
That's a good point.  What about this alternate  proposal: move the syntax xml files into their own repository which can then be incorporated by downstream projects like the one I'm working on and skylighting-core itself (via mechanisms like git submodules).  This would simplify the sharing of those files; the current methodology is to periodically and manually copy the xml subdir of skylighting-core into the needed targets.

**Comment by jgm** [comment]
That's more maintenance burden than I want to take on given that this is a fairly fringe need.  You can script it.

**Comment by kquick** [comment]
That's fair.  Thanks for your consideration, and thanks for skylighting!
