### ISSUE TITLE
Support Racket syntax highlighting by default

### ISSUE THREAD

**Issue by omentic** [jgm/skylighting#194]
[Racket](https://racket-lang.org/) is a descendant of Scheme widely used in academia and education. Looking through past issues, it looks like skylighting does not include everything in the KDE syntax repo for size concerns: but IMO Racket is a major omission (especially given Agda is included!)

(I also think Zig is a pretty big omission, as is Crystal and Gleam, but not to the same level of Racket)

**Comment by jgm** [comment]
Are these in the KDE repository?  If so, we can include them.

**Comment by omentic** [comment]
Yup!
