### ISSUE TITLE
Elm lang and missing span classes?

### ISSUE THREAD

**Issue by badlydrawnrob** [jgm/skylighting#196]
> **TL;DR:** Skylighting is missing some of the "tokens" that other syntax highlighters have.
> I'm comparing it's output with Pandoc to that of Breeze Dark Theme in Visual Studio Code.
> It means some styling is impossible, and others become more difficult.

I've created an [issue here covering some of the issues](https://github.com/badlydrawnrob/anki/issues/152) I'm having generating a custom syntax highlighting theme. I've also mentioned this in a new [Pandoc issue](https://github.com/jgm/pandoc/issues/10114) (which uses Haskell's Skylighting). One such issue is that with Elm Lang `.fu` classes are used for both functions and their arguments, which seems incorrect. With other languages, it seems that some "tokens" (if that's the right word) are missing, use the same `span` classes (when they should use unique ones), or are a little harder to style with Skylighting compared Visual Studio Code, for example.

See the `view model` (VSC is the top image) — you'll also see the `span` is in white. See below for an example:

<img width="605" alt="model-div-span-01-correct-colours" src="https://github.com/user-attachments/assets/c83bcba7-2808-4d3a-b331-c641372915a9">
<img width="595" alt="model-div-span-03" src="https://github.com/user-attachments/assets/df63a5e1-76ec-4367-b35e-508c8efd636c">

**Comment by jgm** [comment]
We use the syntax definitions from KDE.  If you open the file in the Kate editor, you'll see the same kind of highlighting.  If you'd like, you can open an issue at KDE (see the links in our README) and suggest changes to this highlighter.  (If made they would be incorporated here.)  We do not generally make local changes in the xml definitions, but prefer changes to be made upstream.
