### ISSUE TITLE
TLA+ syntax added to `syntax-highlighting`

### ISSUE THREAD

**Issue by younes-io** [jgm/skylighting#199]
TLA+ syntax support has been merged here: https://invent.kde.org/frameworks/syntax-highlighting/-/merge_requests/666

I don't know whether it will be systematically integrated within `Skylighting` or if there will be something else I should do.

**Comment by jgm** [comment]
I'll integrate it.

**Comment by younes-io** [comment]
Thank you @jgm!

A couple of quick questions:
1. Will this commit be included in the upcoming release `0.14.4`?
2. Do you have an estimated timeline for when the next release will be published?
   (I'm asking because `skylighting` is a dependency of a tool, and I need to coordinate with the maintainers to schedule a release with TLA+ support)

Thank you

**Comment by jgm** [comment]
Yes, it will be in the next release.
Not sure about the exact timing, but I'd push out a release  before the next pandoc release, and I would expect that in the next month or so.

**Comment by younes-io** [comment]
thank you for the quick feedback @jgm
