### ISSUE TITLE
Add ANSI output format.

### ISSUE THREAD

**Issue by pthariensflame** [jgm/skylighting#21]
I'd like it if one of the output formats of `skylighting` was ANSI terminal colors; this would let it fully replace one of `highlighting-kate`’s old users, [`cless`](https://github.com/tanakh/cless).

This issue is mostly testing the waters to see if such a thing would be accepted as part of `skylighting` (the executable).  If so, I'd be more than happy to implement it myself; otherwise, I might fork `cless` and attempt to update it to use `skylighting` instead of `highlighting-kate`.

**Comment by jgm** [comment]
+++ Alexander Ronald Altman [Nov 05 17 14:18 ]:
>   I'd like it if one of the output formats of skylighting was ANSI
>   terminal colors; this would let it fully replace one of
>   highlighting-kate’s old users, [1]cless.

I'd be interested in an ANSI terminal formatter for
skylighting, yes!  (It should be part of the library,
and the the executable could use it by specifying 'ansi'
as an output format.)

**Comment by jgm** [comment]
PS. I imagine the tricky part will be converting from a
skylighting Style's Color (RGB) to the fixed palette of ANSI
colors.

**Comment by pthariensflame** [comment]
Did `highlighting-kate` use a similar RGB color system when describing its styles?  If so, I can simply look at what `cless` did and copy/modify that.

**Comment by jgm** [comment]
Yes.

+++ Alexander Ronald Altman [Nov 05 17 21:57 ]:
