### ISSUE TITLE
Documentation typo: The cabal bootstrap method contains three lines

### ISSUE THREAD

**Issue by stefanocoretta** [jgm/skylighting#24]
I tried to follow the cabal bootstrap method to install a custom version of `skylighting` but the code reported in the documentation returned the error `unrecognized 'install' option '--disable-optimizations'`.

Also, the text says that the installation is a two step method, but there are three code of lines.

I tried the following code instead, which seems to have worked (note `--disable-optimization` instead of `--disable-optimizations`):

    cabal run skylighting-extract -- xml/*.xml
    cabal install -f-bootstrap --disable-optimization

Is this the correct way?

**Comment by jgm** [comment]
Yes, thanks.  The "two step" refers to (1) building the
parsers from the xml files (this needs two lines of code
for cabal) and (2) building the library.

+++ Stefano Coretta [Nov 17 17 10:32 ]:
