### ISSUE TITLE
Add no-highlight option

### ISSUE THREAD

**Issue by dbaynard** [jgm/skylighting#48]
`skylighting` does two tasks:

1.  Formats code
2.  Highlights code

At the moment, skylighting does not highlight code without formatting; this causes problems e.g. jgm/pandoc#4688 as the skylighting formatting functionality must be duplicated.

The `skylighting` api should make it possible to format code without highlighting.

**Comment by jgm** [comment]
One approach would be to add a default.xml syntax
description that basically does not highlighting,
derive a syntax from it, and use this as the default.

This would require no other changes to the API, at
the cost of being a bit slower I suppose.

**Comment by dbaynard** [comment]
Is it worth adding something like the following:

```xml
extensions="*.txt" mimetype="text/plain" 
```

here?

https://github.com/jgm/skylighting/blob/3238154b390da1fe62a89ab1b3820c1dedd9366b/skylighting-core/xml/default.xml#L3
