### ISSUE TITLE
failed to build with ghc-7.8.4 (base-4.7.0.2)

### ISSUE THREAD

**Issue by juhp** [jgm/skylighting#5]
skylighting-0.1.1.4 fails to build for me with ghc-7.8:

```
Failed to install skylighting-0.1.1.4
Last 10 lines of the build log ( /builddir/build/BUILD/pandoc-1.19.2.1/.cabal-sandbox/logs/skylighting-0.1.1.4.log ):
    No instance for (PrintfArg Text) arising from a use of ‘printf’
    In the second argument of ‘($)’, namely
      ‘printf "\\textcolor[rgb]{%0.2f,%0.2f,%0.2f}{%s}" r g b x’
    In the expression:
      Text.pack
      $ printf "\\textcolor[rgb]{%0.2f,%0.2f,%0.2f}{%s}" r g b x
    In a case alternative:
        Just (r, g, b)
          -> Text.pack
             $ printf "\\textcolor[rgb]{%0.2f,%0.2f,%0.2f}{%s}" r g b x
```

https://copr-be.cloud.fedoraproject.org/results/petersen/pandoc/fedora-24-x86_64/00506524-pandoc/build.log.gz

**Comment by jgm** [comment]
Interesting, I thought this issue was fixed in 0.1.1.4.
But I see now that it really isn't.

Oddly, though, it builds with ghc 7.8.4 / base 4.7.0.2 on travis:

https://travis-ci.org/jgm/skylighting

Are you on ghc 7.8.3 by chance?

+++ Jens Petersen [Feb 03 17 04:07 ]:

**Comment by juhp** [comment]
No, above build is using ghc-7.8.4.

You can see the system package set being used here:
https://copr-be.cloud.fedoraproject.org/results/petersen/pandoc/fedora-24-x86_64/00506524-pandoc/root.log.gz

**Comment by jgm** [comment]
Actually I can build on travis with ghc 7.8.3 too.
What version of text are you using?  Perhaps at some
point text added an instance for Printf.

I'll just change the code so it doesn't rely on such
an instance.

+++ Jens Petersen [Feb 03 17 04:07 ]:

**Comment by juhp** [comment]
Thanks!

Okay - Fedora 24 has text is 1.1.1.3
whereas Fedora 25+ is on 1.2.2.1.

**Comment by jgm** [comment]
Try skylighting 0.1.1.5, just released.

+++ Jens Petersen [Feb 03 17 05:40 ]:

**Comment by juhp** [comment]
Thanks! :-)

https://copr.fedorainfracloud.org/coprs/petersen/pandoc/build/507501/
