### ISSUE TITLE
Support JSX

### ISSUE THREAD

**Issue by hsribei** [jgm/skylighting#56]
Any plans to support syntax highlighting for the JavaScript XML-like extension used by React?

https://github.com/facebook/jsx

**Comment by jgm** [comment]
If there is a KDE .xml syntax definition for jsx, we
can include it.  I don't see one in KDE's repository,
but you could perhaps create your own.  I would just
ask that in that case you submit it upstream as well
as here, since we try to keep in sync.

**Comment by jgm** [comment]
We have now added javascript-react which supports this.
