### ISSUE TITLE
Support for last KDE syntax set (especially smali)

### ISSUE THREAD

**Issue by iamironz** [jgm/skylighting#69]
Hi. Please, update your syntax highlight set, according to [this](https://github.com/KDE/syntax-highlighting/commits/master/data/syntax) page. I'm especially interesting to smali language syntax because pandoc cannot support this one without your library update.

**Comment by jgm** [comment]
By design, we don't support all of the syntaxes that KDE does. Partly that's to keep compile time and code size down.  If there is a particular syntax you need, you can request it.

**Comment by jgm** [comment]
Note: you can also load a KDE XML syntax definition directly and use it with this library (and with pandoc, `--syntax-definition=`).
