### ISSUE TITLE
skylighting-0.1.1.5 versus ghc 8.0.2

### ISSUE THREAD

**Issue by peti** [jgm/skylighting#7]
Has anyone managed to compile this package with GHC 8.0.2? All our attempts at openSUSE invariably fail with the compiler crashing. At first, these crashes were caused because the builds needs crazy amounts of memory (in excess of 6 GByte). Then, after we've moved it to bigger machines, it just segfaults, i.e. in https://build.opensuse.org/package/live_build_log/devel:languages:haskell:lts:8/ghc-skylighting/openSUSE_Tumbleweed/x86_64:

~~~
[  350s] [ 11 of 132] Compiling Skylighting.Syntax.Asn1 ( src/Skylighting/Syntax/Asn1.hs, dist/build/Skylighting/Syntax/Asn1.p_o )
[  350s] [ 12 of 132] Compiling Skylighting.Syntax.Asp ( src/Skylighting/Syntax/Asp.hs, dist/build/Skylighting/Syntax/Asp.p_o )
[  350s] [ 13 of 132] Compiling Skylighting.Syntax.Ats ( src/Skylighting/Syntax/Ats.hs, dist/build/Skylighting/Syntax/Ats.p_o )
[  655s] /var/tmp/rpm-tmp.knGbre: line 49:  1819 Segmentation fault      ./Setup build -j8 -v
[  655s] error: Bad exit status from /var/tmp/rpm-tmp.knGbre (%build)
~~~~

Am I the only one having that problem?

**Comment by jgm** [comment]
Hm, I haven't experienced problems like this.

We build on 8.0.2 on travis: here's a successful job.
https://travis-ci.org/jgm/skylighting/jobs/202236992

I don't know how much memory those travis build machines
have, but according to
https://docs.travis-ci.com/user/ci-environment/
it's 4 GB.

You could try building without optimizations
(--disable-optimizations on cabal or --fast on stack) to see
if that makes a difference.  (Note however that this will
have a significant effect on performance.)

+++ Peter Simons [Feb 16 17 03:42 ]:

**Comment by jgm** [comment]
Ah, but that travis build has disabled optimizations.
I changed travis to use optimizations, let's see if that makes a difference:
https://travis-ci.org/jgm/skylighting/builds/202257309

**Comment by jgm** [comment]
It does seem to be building very slowly on 8.0.2.
Odd thing:  that is only on the 8.0.2 build with cabal.
The stack lts-8 build with ghc 8.0.2 proceeds with no problem.
I've added a cabal 8.0.1 build for comparison.

**Comment by jgm** [comment]
See https://travis-ci.org/jgm/skylighting/builds/202266804
No real difference between 8.0.1 and 8.0.2; however, both take quite a bit longer to compile than 7.x.
What I really don't understand is why the stack lts-8 build (with 8.0.2) is so much faster.

**Comment by juhp** [comment]
For me it is compiling the prof library that uses large amount of ram.

I may have to ship pandoc-1.19.1 in Fedora 26 to avoid this.

**Comment by jgm** [comment]
@juhp - that really helps to know that the problem concerns profiling builds.

We're not doing any manual INLINEing in this library.

Can you confirm that you don't have this problem with profiling builds on earlier ghc versions?

**Comment by jgm** [comment]
@peti are your problems also related to profiling builds?

**Comment by jgm** [comment]
I added a profiling build to Travis.  It is taking a long time indeed:
https://travis-ci.org/jgm/skylighting/jobs/203176773

**Comment by jgm** [comment]
Possibly relevant: http://stackoverflow.com/questions/16348340/compiling-very-large-constants-with-ghc

**Comment by juhp** [comment]
Thanks!! - 0.2 builds easily for me in a 2GB VM. 👍

**Comment by jgm** [comment]
@juhp - really?  That is surprising, because the 0.2 fixes didn't affect the problem for me:
https://travis-ci.org/jgm/skylighting/builds/203261404

@peti can you try with 0.2?

I do have a 'read' branch which adopts the suggestions in  http://stackoverflow.com/questions/16348340/compiling-very-large-constants-with-ghc and compiles very quickly.  However, there is currently some runtime penalty.  I'm going to try to figure out how to eliminate that.

**Comment by jgm** [comment]
OK, I just released skylighting 0.3, which should fix the problem.

It's too bad that ghc is so bad at handling libraries with lots of long literals.

**Comment by peti** [comment]
Will skylighting-0.3 make it into the Stackage LTS 8.x release branch?

**Comment by jgm** [comment]
Hm, I don't know what their policy is on this.  I think they
normally don't admit major-version updates until the next
lts version.  We could perhaps lobby them to do so in this
case because of the compiling problems (and because the API
changes are so minor, mostly a matter of instances).

+++ Peter Simons [Feb 20 17 05:11 ]:

**Comment by jgm** [comment]
In any case the pandoc that's in lts-8 excludes this version
of skylighting with version bounds...

+++ Peter Simons [Feb 20 17 05:11 ]:

**Comment by peti** [comment]
Well, that's a shame. Version 0.3 *does* fix the build problem for us and it would be nice to be able to use it.

**Comment by jgm** [comment]
Doesn't your setup allow setting up patches for specific
packages?  I build pandoc with a stack.yaml that adds
skylighting-0.3 in extra-deps.  That works fine.

+++ Peter Simons [Feb 20 17 10:34 ]:

**Comment by juhp** [comment]
If 0.3 does not break any API compared to 0.1 then it would probably be okay to update lts-8.
I guess in practice only pandoc is using skylighting (currently) so it would not be such a big deal even to have minor break API, but there has been criticism of other API breaking version updates to LTS.

**Comment by mpickering** [comment]
I can't quite work out from the discussion here. Was the problem that the profiled build took a long time? What exact command do I need to reproduce the problem (preferably using cabal).

**Comment by juhp** [comment]
@mpickering building prof took a lot of RAM - maybe something like `cabal install -p skylighting-0.1.1.3`.
I have not tried to reproduce again. Anyway I believe the problem is fixed now.

**Comment by jgm** [comment]
+++ Jens Petersen [Mar 01 17 18:50 ]:
>   I have not tried to reproduce again. Anyway I believe the problem is
>   fixed now.

I'd say it's "sort of fixed."

We're doing something quite unnatural (and something that
has an impact on performance) in order to make it possible
to compile the library with reasonable resources.

This is a problem with GHC.  GHC should be able to handle
case; it's a simple library with over a hundred modules,
each of which does nothing more than define a data
structure.

I suspect there's some kind of space like in GHC, because
at first compilation goes relatively fast; as we get into
the 50th or 60th module, it really slows down.  The modules
don't differ much from each other, so that suggests to me
that it's the sheer number of them that matters.

@mpickering

**Comment by mpickering** [comment]
We did some experimentation already with the `0.1.1.5` version and even compiling `Skylighting.Types` with profiling enabled used over 4gb of memory. We suspect that there might be some improvements in the 8.2 release so will try again then.

**Comment by jgm** [comment]
+++ Matthew Pickering [Mar 02 17 02:07 ]:
>   We did some experimentation already with the 0.1.1.5 version and even
>   compiling Skylighting.Types with profiling enabled used over 4gb of
>   memory. We suspect that there might be some improvements in the 8.2
>   release so will try again then.

@mpickering, glad to hear of this work!

It's a bit puzzling, though, what you say about
Skylighting.Types.  I haven't had any complaints about the
new version of skylighting, but Skylighting.Types hasn't
changed.

**Comment by ddssff** [comment]
Oh, now I see why ghcjs builds skylighting so much quicker than ghc - no profiling.

**Comment by treeowl** [comment]
@bgamari opened [GHC Trac #13639](https://ghc.haskell.org/trac/ghc/ticket/13639) to look into this.

**Comment by niteria** [comment]
I believe 8.2 won't run into this performance problem on `skylighting-0.1.1.5`.

**Comment by juhp** [comment]
BTW pandoc-1.19.2.4 seems to build just fine with newer versions of skylighting: so the upperbound could be relaxed
