### ISSUE TITLE
Syntax Highlighting for Stata

### ISSUE THREAD

**Issue by randrescastaneda** [jgm/skylighting#74]
Dear all, 

Is it possible to add Stata syntax highlighting to skylighting? I say someone tried to do so in #47 but I could not find any follow up. 

Thank you so much for your help. 

Best, 
Andres

**Comment by jgm** [comment]
First thing is to check the KDE repository to see if they have a stata.xml syntax definition.
See the documentation for this library for information on how to find that repo.
If there is one, it should be easy to include.

**Comment by randrescastaneda** [comment]
HI @jgm, 

[Kyle Barron](https://github.com/kylebarron), the person who raised issue #47, suggested the following [xml repo ](https://github.com/KDE/syntax-highlighting/blob/master/data/syntax/stata.xml). Does it work? 

Thank you so much. 

Best,

**Comment by jgm** [comment]
Since you have the xml file, you can already use it to do stata highlighting with skylighting.
See `loadSyntaxFromFile`.
Or, with pandoc, the `--syntax-definition` option.

We could consider adding it as a compiled module -- I try to add things only when needed, to keep the size of the package down, but if this is the second request it's probably enough for me.

**Comment by sunnyarlington** [comment]
I really this package as well. It would be appreciated if you can add this. Thank you.

**Comment by JavierParada** [comment]
Dear John @jgm,
I agree that adding Stata syntax highlighting to skylighting would be very useful. 
Thanks!

**Comment by randrescastaneda** [comment]
Thank you so much, @jgm, for adding the Stata syntax highlighting. 

One final question (please, forgive my ignorance), does Pandoc get updated automatically? I am using Rstudio to execute Pandoc, but I think either Pandoc or Rstudio (or both), must be updated for the Stata syntax be taken into account, right? Do you have any guidance on this? 

Thanks again. 
Best,

**Comment by jgm** [comment]
This will be in the next release of pandoc, but in the
mean time you need to use --syntax-definition
stata.xml as noted above.

**Comment by randrescastaneda** [comment]
Awesome. Thank you  so much. 

However, when I tried to use the `--syntax-definition=stata.xml`  I got the following error: Am I doing something wrong? 

![image](https://user-images.githubusercontent.com/35301997/58748209-1d413a00-8443-11e9-892a-1f8066bbf232.png)

Thank you so much. 

Best,

**Comment by jgm** [comment]
Are you using the latest pandoc?

Should be fixed by now:
https://github.com/jgm/pandoc/issues/5328

If not, there's a link to language.dtd in that thread;
just put it in your working directory with stata.xml.
