### ISSUE TITLE
[HTML] Highlighted inline code within strikeout is not applied correctly

### ISSUE THREAD

**Issue by mpark** [jgm/skylighting#79]
Consider: ``~~foo `constexpr`{.cpp} bar~~``
With `pandoc foo.md --output foo.html --self-contained` this currently generates:
<img width="130" alt="Screen Shot 2019-06-13 at 10 46 58 PM" src="https://user-images.githubusercontent.com/2275240/59486277-a9813300-8e2d-11e9-888e-909d0292bf68.png">

The desired output would be something like:
<img width="131" alt="Screen Shot 2019-06-13 at 10 47 19 PM" src="https://user-images.githubusercontent.com/2275240/59486299-bc940300-8e2d-11e9-9256-6397d479bbd4.png">

---

This seems to be caused by the `display: inline-block` from https://github.com/jgm/skylighting/blob/8c650b6e4aafc4c5eafb82d6e3449f3a67e066ee/skylighting-core/src/Skylighting/Format/HTML.hs#L170.
Changing this to `display: inline` produces the desired output.

**Comment by jgm** [comment]
@dbaynard may be able to say more than I can about why `display: block` is in there...

**Comment by dbaynard** [comment]
This is a bug, introduced in 0b07bbc8 when the line `span` tags were simplified — I didn't notice the clash.

```html
<code class="sourceCode cpp"><span class="kw">constexpr</span></code>
```

This is treating the span as a line. The css should probably restrict it to `pre > code.sourceCode > span`. I'm making the PR, now.

**Comment by dbaynard** [comment]
There's also some browser variation, it seems.
