### ISSUE TITLE
Invalid highlighting for '\0'

### ISSUE THREAD

**Issue by zvad11** [jgm/skylighting#82]
```
'\0'
```
in the c language wrongly highlights the last quote to be invalid.

**Comment by jgm** [comment]
Confirmed that this works in Kate.

**Comment by jgm** [comment]
Found the bug, in   pCStringChar.

**Comment by jgm** [comment]
Thanks for reporting this!  It was a regression that has been present since 2017, affecting multiple syntaxes (not just C).  Surprising it hasn't come up before now.

**Comment by jgm** [comment]
Released 0.8.1.2 with fix.
