### ISSUE TITLE
Markdown: first list item marker in fenced code block parsed differently

### ISSUE THREAD

**Issue by matoushs** [jgm/skylighting#84]
The first list item marker inside a fenced code block is processed differently than the others. A list within a code block with a markdown class places the span after the first list marker (1.), but with other classes the list marker (1.) is placed as content in the <span> tag. 

I compiled the following code with: pandoc -f markdown -t html 
~~~
# Testing Fenced Code Blocks
  
```markdown
Ordered List - Markdown
1.  bread
2.  milk
3.  sugar
```

```javascript
Ordered List - Javscript
1.  bread
2.  milk
3.  sugar
```

```markdown
Enumerated List - Markdown
-  Take out trash
-  Vaccuum
    - Bedrooms
-  Wash dishes
```
~~~

This produces: 

![image](https://user-images.githubusercontent.com/15343188/61445981-b3c3af00-a94e-11e9-93d2-0be69b3cc859.png)

Ordered List - Markdown
```html
<pre class="sourceCode markdown"><code class="sourceCode markdown"><a class="sourceLine" id="cb1-1" title="1">Test Paragraph</a>
<a class="sourceLine" id="cb1-2" title="2">1. <span class="fl"> bread</span></a>
```
Ordered List - Javscript
```html
<pre class="sourceCode javascript"><code class="sourceCode javascript"><a class="sourceLine" id="cb2-1" title="1">Test Paragraph</a>
<a class="sourceLine" id="cb2-2" title="2"><span class="fl">1.</span>  bread</a>
```
Enumerated List - Markdown
```html
<pre class="sourceCode markdown"><code class="sourceCode markdown"><a class="sourceLine" id="cb3-1" title="1">Test Paragraph</a>
<a class="sourceLine" id="cb3-2" title="2">- <span class="fl"> Take out trash</span></a>
```

See that in the first and third examples the list marker "1." appears before the span, but in the second example it appears within the span. This produces correct syntax highlighting.

My setup is: 
macOS Mojave 10.14.5
pandoc 2.7.1

**Comment by jgm** [comment]
I just tried this in Kate and it appears to work there, so this might be an issue in skylighting rather than the markdown.xml syntax definition.

**Comment by jgm** [comment]
Relevant bits of trace output:
```
...
FALLTHROUGH Just (NormalTok,"Hi")
...
Trying rule Rule {rMatcher = RegExpr (RE {reString = "[\\d]+\\.\\s", reCaseSensitive = True}), rAttribute = NormalTok, rIncludeAttribute = False, rDynamic = False, rCaseSensitive = True, rChildren = [], rLookahead = False, rFirstNonspace = False, rColumn = Just 0, rContextSwitch = [Push ("Markdown","numlist")]}
RegExpr MATCHED Just (NormalTok,"1. ")
CONTEXT STACK ["numlist","Normal Text"]
FALLTHROUGH Just (StringTok," ")
etc.
```
As far as I can see, we're interpreting the syntax definition correctly.  First we match on
``` xml
      <context attribute="Normal Text" lineEndContext="#stay" name="Normal Text">
        <RegExpr context="numlist" String="^[\d]+\.\s"/>
```
Since the `RegExpr` element has no `attribute`, the parent attribute `Normal Text` is used for what matches here (`1.`).  Then we switch to the "numlist" context and from then on everything has the `String` attribute (which this definition uses for numbered lists).

But since Kate works, maybe there's a problem in my understanding of how this is supposed to be interpreted.

**Comment by jgm** [comment]
It's an easy matter to fix markdown.xml, but I'm still puzzled as to why Kate works.
