### ISSUE TITLE
Bogus system-pcre flag in skylighting?

### ISSUE THREAD

**Issue by lierdakil** [jgm/skylighting#87]
https://github.com/jgm/skylighting/blob/c41e2dab68bfea9612021e1bbaba5305f4eed269/skylighting/skylighting.cabal#L195-L197

It would appear that this flag does nothing now, unless I've missed an `#ifdef` in the code (grep didn't find any).

Things depending on this flag were removed in 67d4b9dc9735ac6e244daad68e52d5eec727dc82

**Comment by jgm** [comment]
Thanks.  I removed it.  (This flag does affect skylighting-core.)
