### ISSUE TITLE
Fails to build with GHC 8.8.1

### ISSUE THREAD

**Issue by mrkkrp** [jgm/skylighting#88]
`skylighting-core` fails to build with GHC 8.8.1:

https://travis-ci.org/mmark-md/mmark-ext/jobs/590377801#L376

It's a good idea to enable that version of GHC in the CI.

**Comment by jgm** [comment]
I'm working on this.  Once I get the CI ironed out, I will put out a release that builds with 8.8.

**Comment by jgm** [comment]
0.8.2.3 builds with ghc 8.8.
