### ISSUE TITLE
Any future support for vimscript?

### ISSUE THREAD

**Issue by MisanthropicBit** [jgm/skylighting#89]
I have a Hakyll blog which contains some vimscript/VimL (the scripting language of the vim editor) but the code is not highlighted since skylighting does not yet support it AFAIK. Neither is the language in this [KDE syntax highlighting repository](https://github.com/KDE/syntax-highlighting/tree/master/data/syntax).

Are there any chances this will be supported at some point?

Vimscript is hard to highlight since many commands can be abbreviated. For example, the [vimL lexer](https://bitbucket.org/birkenfeld/pygments-main/src/default/pygments/lexers/textedit.py) in [pygments](http://pygments.org/) auto-generates a [list of commands etc.](https://bitbucket.org/birkenfeld/pygments-main/src/default/pygments/lexers/_vim_builtins.py) that is then checked, which may or may not be possible in KDE. Alternatively, one could choose to only support non-abbreviated commands.

**Comment by jgm** [comment]
You might start by contributing a highlighting syntax definition for vimscript to KDE.

**Comment by MisanthropicBit** [comment]
True. I actually have one going on [here](https://github.com/MisanthropicBit/skylighting) (local commits pending) for skylighting itself but I cannot currently solve the abbreviation problem elegantly.

I'll continue to work on my fork, ignoring abbreviated commands, and submit a PR when it's ready.
