### ISSUE TITLE
Opening double quotes in sqlpostgresql code block are highlighted as comment

### ISSUE THREAD

**Issue by bewuethr** [jgm/skylighting#95]
Pandoc version: 2.9.2.1

### To reproduce

Render a code block with syntax highlighting language `sqlpostgresql` with a double quoted string.

~~~bash
pandoc <<'EOF'
```sqlpostgresql
select 'foo' "bar";
```
EOF
~~~

### Expected behaviour

Double quoted string is assigned class `ot` ("other"), as it does for `sql`:

```html
<span class="ot">&quot;bar&quot;</span>
```

which renders like

![sql double quotes](https://user-images.githubusercontent.com/8521043/81508518-89beed00-92d2-11ea-87c7-d64230092723.png)

with default styling, or class `st` ("string"), as for `sqlmysql`:

```html
<span class="st">&quot;bar&quot;</span>
```

which renders like

![sqlmysql double quotes](https://user-images.githubusercontent.com/8521043/81508486-5da36c00-92d2-11ea-9ea1-2690f9ae256a.png)

### Observed behaviour

The opening double quote is assigned class `co` ("comment"), the string and the closing double quote `ot` ("other"):

```html
<span class="co">&quot;</span><span class="ot">bar&quot;</span>
```

which renders like

![sqlpostgresql double quotes](https://user-images.githubusercontent.com/8521043/81508568-d1457900-92d2-11ea-997e-26b6fd50fa7e.png)

with default settings, or more obviously incorrect, as

![sqlpostgresql double quotes, my styling](https://user-images.githubusercontent.com/8521043/81508602-fcc86380-92d2-11ea-8b3b-25501530e16b.png)

with a styling where italics visibly change double quotes.

**Comment by bewuethr** [comment]
The [upstream syntax file](https://phabricator.kde.org/source/syntax-highlighting/browse/master/data/syntax/sql-postgresql.xml) is identical to what Skylighting uses, i.e., there nothing more recent in there than here, an indeed, also when using Kate, the highlighting is wrong:

![image](https://user-images.githubusercontent.com/8521043/81516580-5302ca00-9306-11ea-9a62-c680702574ad.png)

The offending line

```xml
       <DetectChar attribute="Comment" context="Identifier" char="&quot;"/>
```

has been like this ever since it was added to the syntax highlighting repo in 2016 in [this commit](https://phabricator.kde.org/R216:7af3457977a7141e7d7472b80c175aaad3ace822) from a not further specified "upstream"; I'll see where and how I can report this to the KDE project then.

**Comment by jgm** [comment]
You could try writing to the author of the syntax definition - email is listed at the beginning of the xml file.

**Comment by bewuethr** [comment]
I'll try! The syntax file is ancient, it was initially added in 2002 to, back then, Kate (see [history](https://github.com/KDE/kate/commits/cd7ed15b1ebc45ed9fdd9a6a8d58e739bc92d8a0/part/data/sql-postgresql.xml)), and the line we think might be responsible for the incorrect quoting was [added in 2003](https://github.com/KDE/kate/commit/2e55bd0ca7deaaffe5546f04e2925112cca2a9a6#diff-23999c6941df50d23a602798ad93d229), so it's been like this for a long time.

**Comment by jgm** [comment]
Makes sense.  If you want to submit a PR here we can update it locally; but it would also be good to get it changed in KDE, since we periodically refresh from upstream and it's a pain if we get out of sync.

For an example of the kind of thing that would be needed, see skylighting-core/xml/bash.xml.patch.  IF you just add a patch like this, produced by diff against the changes you would make to the xml file, it will be applied when e build.

**Comment by bewuethr** [comment]
Submitted as [a KDE bug](https://bugs.kde.org/show_bug.cgi?id=421445). I'll submit an upstream patch and a PR for Skylighting later this week.

**Comment by bewuethr** [comment]
[KDE differential](https://phabricator.kde.org/D29735) submitted.
